<?php
/**
 * @file
 * API documentation for the DD Panels module.
 */

/**
 * Allows module to add extra fields to the DD Flexible Style settings form.
 */
function hook_dd_flexible_style_settings_form_alter(&$form, &$form_state, $type, $style_settings) {
}

/**
 * Allows module to alter the attributes generated by the Flexible Style plugin.
 */
function hook_dd_flexible_style_attributes_alter(&$attributes, $settings, $info) {
  $type = $info['type'];
}

/**
 * Allows module to alter the default settings for the Flexible Style plugin.
 */
function hook_dd_flexible_style_default_settings_alter(&$settings, $type) {
}
