<?php

/**
 * Implements hook_dd_flexible_style_settings_form_alter().
 */
function dd_flexible_style_next_dd_flexible_style_settings_form_alter(&$form, &$form_state, $details, $style_settings) {
  $type = $details['type'];

  if ($type == 'row') {
    $form['next'] = array(
      '#type' => 'checkbox',
      '#title' => t('Add link to next row'),
      '#default_value' => (isset($style_settings['next'])) ? $style_settings['next'] : 0,
      '#description' => t('Add a arrow link to the bottom of the row which links to the next one.'),
    );
  }
}

/**
 * Implements hook_dd_flexible_style_wrappers_alter().
 */
function dd_flexible_style_next_dd_flexible_style_wrappers_alter(&$wrappers, $settings, $info) {
  if (!empty($settings['next'])) {
    $type = dd_panels_get_region_type($info['region_id']);
    $next_row = $type['row'] + 1;
    $wrappers['inner_suffix_array'][] = '<div class="next-row"><a href="#row-' . $next_row . '"></a></div>';
  }
}
